FROM ace-minimal:11.0.0.5-alpine-openjdk

ARG LICENSE

# Switch off the admin REST API for the server run, as we won't be deploying anything after start
RUN sed -i 's/#port: 7600/port: -1/g' /home/aceuser/ace-server/server.conf.yaml 

COPY aceFunction.bar /tmp/aceFunction.bar
RUN bash -c "export LICENSE=${LICENSE} && mqsibar -c -a /tmp/aceFunction.bar -w /home/aceuser/ace-server"

# Set entrypoint to run the server
ENTRYPOINT ["bash", "-c", "IntegrationServer -w /home/aceuser/ace-server"]



