FROM ace-only:latest

USER root

COPY bars_aceonly /home/aceuser/bars
RUN  chmod -R ugo+rwx /home/aceuser

USER aceuser

RUN ace_compile_bars.sh

USER root

RUN  chmod -R ugo+rwx /home/aceuser

USER aceuser